# Generated by Django 4.0.4 on 2022-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('restaurant_owner', 'restaurant_owner'), ('customer', 'customer'), ('admin', 'admin')], default='sapid_app', max_length=20),
        ),
    ]
